author: Bw2801
database: false
description: Censores customizable words in chat.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.bw2801.plugins.censorship.Censorship
name: CensorShip
startup: postworld
version: '1.9.3'

permissions:
  censor.disallow:
    description: disallows to get kicked or banned for using forbidden words.
    default: op
  censor.add:
    description: allows to add forbidden words.
    default: op
  censor.remove:
    description: allows to add forbidden words.
    default: op
  censor.update:
    description: allows to update forbidden words.
    default: op
  censor.penalty-points.add:
    description: allows to add penalty points to given player.
    default: op
  censor.penalty-points.remove:
    description: allows to remove penalty points to given player.
    default: op
    
commands:
  censor:
    description: adds/removes forbidden words.